# Generated by Django 6.0.1 on 2026-01-20 12:24

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0002_class_max_students_class_total_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='VD: Midterm, Final, Lab1', max_length=100)),
                ('weight', models.FloatField(help_text='Trọng số của các cột điểm')),
                ('week_number', models.PositiveIntegerField(blank=True, help_text='Thuộc tuần nào nếu có', null=True)),
            ],
            options={
                'ordering': ['week_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['week_number']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='component',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_obj', 'week_number')},
        ),
        migrations.AddField(
            model_name='grade',
            name='grading_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.gradingitem'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'class_obj', 'grading_item')},
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_week', models.PositiveIntegerField(help_text='Số tuần chuẩn (10 / 15/ ...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='VD: v1.0, v1.1', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_syllabus_version', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='versions', to='academics.syllabus')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('syllabus', 'version')},
            },
        ),
        migrations.AddField(
            model_name='gradingitem',
            name='syllabus_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_items', to='academics.syllabusversion'),
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('reference_materials', models.TextField(blank=True, help_text='Link, sách, tài liệu tham khảo')),
                ('syllabus_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='academics.syllabusversion')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('syllabus_version', 'week_number')},
            },
        ),
    ]
