# Generated by Django 6.0.1 on 2026-01-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(default=1, verbose_name='Sĩ số tối đa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='total_sessions',
            field=models.PositiveIntegerField(default=1, verbose_name='Tổng số buổi học'),
            preserve_default=False,
        ),
    ]
