# Generated by Django 6.0.1 on 2026-01-20 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_gradingitem_subject_alter_attendance_options_and_more'),
        ('classes', '0002_class_max_students_class_total_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='syllabus_version',
            field=models.ForeignKey(blank=True, help_text='Phiên bản chương trình học đang áp dụng trong lớp này', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.syllabusversion'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Tên hiển thị của Lớp (VD: Python cơ bản - PY01)', max_length=255),
        ),
    ]
