# Generated by Django 6.0.1 on 2026-01-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_created_at_class_syllabus_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_obj', to='classes.class'),
        ),
    ]
