# Generated by Django 6.0.1 on 2026-01-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_enrollment_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class'),
        ),
    ]
