# Generated by Django 6.0.1 on 2026-01-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_class_max_students_class_total_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')], verbose_name='Thứ')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('room', models.CharField(max_length=50, verbose_name='Phòng học')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu học')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('cancelled', 'Giảng viên vắng'), ('makeup', 'Buổi bù')], default='scheduled', max_length=20)),
                ('absence_reason', models.TextField(blank=True, help_text='Lý do giảng viên vắng (nếu có)', null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.class')),
            ],
        ),
    ]
